Se cambio el model de trasncripcion por AssemblyAI, se modifico el prompt de deepseek para mayor entendimiento de los comandos, se cambio scripts y se comentó en el docker-compose el servicio de stt el cual fue reemplazado por AssemblyAI

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -30,38 +30,38 @@ services:
       - OLLAMA_HOST=http://deepseek:11434
     restart: "no"
 
-  stt:
-    image: ghcr.io/speaches-ai/speaches:latest-cpu
-    container_name: faster-whisper-local
-    restart: unless-stopped
-    ports:
-      - "8000:8000"
-    environment:
-      - SPEACHES_MODELS__TRANSCRIBE__DEFAULT=Systran/faster-whisper-small
-      - SPEACHES_MODELS__TRANSCRIBE__AUTO_DOWNLOAD=true
-      - SPEACHES_MODELS__TRANSCRIBE__FORCE_LANGUAGE=es
-      - SPEACHES_CACHE_DIR=/root/.cache/huggingface
-    volumes:
-      - hf-cache:/root/.cache/huggingface
-    healthcheck:
-      test: [ "CMD-SHELL", "curl -sf http://127.0.0.1:8000/health || curl -sf http://127.0.0.1:8000/ || exit 1" ]
-      interval: 5s
-      timeout: 3s
-      retries: 30
-      start_period: 10s
-
-  stt-warmup:
-    image: curlimages/curl:8.10.1
-    depends_on:
-      stt:
-        condition: service_healthy
-    command: >
-      sh -c "
-        echo 'Warming up Systran/faster-whisper-small...';
-        curl -sS -X POST http://stt:8000/v1/models/Systran/faster-whisper-small &&
-        echo 'Warmup OK' || (echo 'Warmup FAILED' && exit 1)
-      "
-    restart: "no"
+#  stt:
+#    image: ghcr.io/speaches-ai/speaches:latest-cpu
+#    container_name: faster-whisper-local
+#    restart: unless-stopped
+#    ports:
+#      - "8000:8000"
+#    environment:
+#      - SPEACHES_MODELS__TRANSCRIBE__DEFAULT=Systran/faster-whisper-small
+#      - SPEACHES_MODELS__TRANSCRIBE__AUTO_DOWNLOAD=true
+#      - SPEACHES_MODELS__TRANSCRIBE__FORCE_LANGUAGE=es
+#      - SPEACHES_CACHE_DIR=/root/.cache/huggingface
+#    volumes:
+#      - hf-cache:/root/.cache/huggingface
+#    healthcheck:
+#      test: [ "CMD-SHELL", "curl -sf http://127.0.0.1:8000/health || curl -sf http://127.0.0.1:8000/ || exit 1" ]
+#      interval: 5s
+#      timeout: 3s
+#      retries: 30
+#      start_period: 10s
+#
+#  stt-warmup:
+#    image: curlimages/curl:8.10.1
+#    depends_on:
+#      stt:
+#        condition: service_healthy
+#    command: >
+#      sh -c "
+#        echo 'Warming up Systran/faster-whisper-small...';
+#        curl -sS -X POST http://stt:8000/v1/models/Systran/faster-whisper-small &&
+#        echo 'Warmup OK' || (echo 'Warmup FAILED' && exit 1)
+#      "
+#    restart: "no"
 
   db:
     image: postgres:16
@@ -85,7 +85,7 @@ services:
     build: .
     container_name: walkie_backend-IA
     ports:
-      - "8086:8080"
+      - "80:8080"
     env_file:
       - .env
     depends_on:
@@ -93,15 +93,16 @@ services:
         condition: service_healthy
       deepseek-setup:
         condition: service_completed_successfully
-      stt:
-        condition: service_started
+#      stt:
+#        condition: service_started
       db:
         condition: service_healthy
     environment:
       - PORT=8080
       - DATABASE_URL=postgres://gopenux:gopenux1234@db:5432/walkie_db?sslmode=disable
       - DEEPSEEK_API_URL=http://deepseek:11434
-      - STT_API_URL=http://stt:8000/v1/audio/transcriptions
+      - ASSEMBLYAI_API_KEY=${ASSEMBLYAI_API_KEY}
+#      - STT_API_URL=http://stt:8000/v1/audio/transcriptions
 
 volumes:
   ollama:
